name: Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7

      - name: Check that the generated files are up to date
        run: nix develop -c ./scripts/check-go-generate.sh

      - name: Build
        run: nix build

      - name: Lint
        run: nix develop -c golangci-lint run
